apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    - rolearn: arn:aws:iam::437064342081:role/eksctl-my-eks-cluster-nodegroup-my-NodeInstanceRole-R11B3FhYJbcG
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::437064342081:user/github-actions-user
      username: github-actions-user
      groups:
        - system:masters
